#!/bin/bash
if [ $# -eq 1 ]
then
repo=$1
/show/description "Pushing current directory into $1"
git init
git add .
git commit -m "First autocommit by pigetBot"
git remote add origin https://github.com/$repo.git
git push -u origin alpha
else
/show/errorBox "Wrong Arguments"
/show/usage "gitInit myusername repo"
/show/example "gitInit pigetnet core"
fi
