#!/bin/bash

if [ $# -eq 1 ];then
	git checkout -b $1
	git add -A
	git commit
	if [ $? -eq 0 ];then
		git push --set-upstream origin alpha
	fi
else
	echo "Specify branch : /do/git/createBranch alpha"
fi
