#!/bin/bash
if [ $# -ge 1 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox '$0'
	/show/info '[alpha] [interactive]'
	/show/usageDescription 'Configure git client (name/email)'
	/show/usage "$0 myusername/repo"
	/show/example "$0 pigetnet/core"
else
	repo=$1
	/show/description "Pushing current directory into $1"
	git init
	git add .
	git commit -m "First autocommit by pigetBot"
	git remote add origin https://github.com/$repo.git
	git push -u origin alpha
fi
