#!/bin/bash
if [ $# -ge 2 ] || [ $# -eq 0 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox "$0"
	/show/info "[beta] [interactive] [danger]"
	/show/usageDescription "Empty a branch in github (use this with caution!)"
	/show/usage "$0 repo branch"
	/show/example "$0 pigetnet/git master"
else
	repo=$1
	branch=$2
	/show/description "EMPTY --> GITHUB:$branch:$repoName"
	/show/listecho "This will erase all file on this branch !" $ERR
	read -r -p "Continue? [Y/n] " response
		case $response in
		[yY])
			/show/listecho "GITHUB:$branch:$reponame ---> /tmp/empty"
			rm -rf /tmp/empty
			git clone https://github.com/$repo -b $branch
			cloneErr=$?
			if [ $cloneErr -eq 0 ];then
				/show/listecho "Add readme.md"
				echo "No release, check alpha/beta branches" > /tmp/empty/readme.md
			else
				/show/listecho "Cannot clone $branch:$reponame"
			fi
		else
			/show/listecho "Repo not Empty" $ERR
			tail /tmp/piget.log
		fi
		else
			/show/listecho "Nothing to save" $WARN
		fi
			;;
		*)
			echo ""
			/show/colecho "Stopped..." $info
			echo -ne $NORMAL
			;;
		esac	
	else
		/show/listecho "This is not a git repo" $ERR
	fi
fi