#!/bin/bash

if [ $# -ge 1 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox "$0"
	/show/info "[beta] [danger]"
	/show/usageDescription "Force push to github (this will erase change on github)"
	/show/usage "$0"
else
	if [[ -e ".git/config" ]];then
		repoName=$(/do/git/name)
		/show/description "LOCAL:$repoName -FORCE-> GITHUB:$repoName"

		/system/logInit "$0 $repoName"

		git push -f >> /tmp/piget.log 2>&1
		pushErr=$?
		if [ $pushErr -eq 0 ];then
			/show/listecho "Repo saved" $WARN
		else
			/show/listecho "Repo not saved" $ERR
			tail /tmp/piget.log
		fi
	else
		/show/listecho "This is not a git repo" $ERR
	fi
fi


