#!/bin/bash
if [ $# -ge 1 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox "$0"
	/show/info '[beta] [danger]'
	/show/usageDescription 'Force Update current folder (this will erase all local changes!)'
	/show/usage "$0"
else
	if [[ -e ".git/config" ]];then
		repoName=$(/do/git/name)
		/show/description "GITHUB:$repoName -FORCE-> LOCAL:$repoName"
		git fetch --all
		git reset --hard origin/master
		git pull
		/show/listecho "$repoName has been updated" $OK
	else
		/show/listecho "Not a git repo" $ERR
	fi
fi