#!/bin/bash

if [ $# -ge 1 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
  /show/messagebox "$0"
  /show/info '[alpha] [wip]'
  /show/usageDescription 'Analyse scripts on current directory and generate a verbose readme file'
  /show/usage "$0"
else
  /show/description "Generate readme for current directory"
  currentDir=$(/show/dir)

  if [ -f "readme.md" ];then
    /show/listecho "Erase previous readme.md" $WARN
    rm doc.md
  fi

  for scripts in *
  do
      if test -f "$scripts"
      then
	      if [[ $scripts != "readme.md" ]] || [[ $scripts != "doc.md" ]];then
		      /show/listecho "Scanning $currentDir/$scripts"
	        /show/helpVerbose "$currentDir/$scripts" >> doc.md
		      echo "" >> doc.md
    	  fi
      fi
  done

fi

/show/listecho "doc.md finished" $OK
