#!/bin/bash

if [ $# -ge 1 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
  /show/messagebox "$0"
  /show/info '[alpha] [wip]'
  /show/usageDescription 'Analyse scripts on current directory and generate a readme file'
  /show/usage "$0"
else
  /show/description "Generate readme for current directory"
  currentDir=$(/show/dir)

  if [ -f "./doc/manual.md" ];then
    /show/listecho "Erase previous manual.md" $WARN
    rm ./doc/manual.md
  fi

  /system/makedir ./doc



  for scripts in *
  do
      if test -f "$scripts"
      then
	      if [[ $scripts != "readme.md" ]] || [[ $scripts != "doc.md" ]];then
		/show/listecho "Scanning $currentDir/$scripts"
	        /show/help "$currentDir/$scripts" >> ./doc/manual.md
		echo "" >> ./doc/manual.md
    	  fi
      fi
  done

fi

/show/listecho "manual.md finished" $OK
