#!/bin/bash
if [ $# -ge 1 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox "$0"
	/show/info '[beta] [return]'
	/show/usageDescription 'Display current directory Repository name'
	/show/return "reponame"
else
	cat .git/config |grep "url"|awk '{print $3}'|sed 's+https://github.com/++'|sed 's/.git//'
fi