#!/bin/bash
/show/description "Nuke last commit ?"
. /show/continuePrompt
/show/listecho "Are you really sure ?" $ERR
. /show/continuePrompt
/show/listecho "git reset --hard HEAD~1"
git reset --hard HEAD~1
/do/git/save