#!/bin/bash
/show/description "Push everything to repo"
/show/listecho "git add -A" $OK
/show/listecho "git commit" $OK
/show/listecho "git push" $OK
git add -A
read
git commit
if [ $? -eq 0 ];then
	git push
fi
