#!/bin/bash

if [ $# -ge 1 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox "$0"
	/show/info '[beta] [interactive]'
	/show/usageDescription 'Configure git client (name/email)'
	/show/usage "$0"
else
	/show/description "Git Client Setup"
	/system/install git

	#Ask for info
	. /show/askUser "Github nickname (not your email)"
	name=$ASKUSER
	. /show/askUser "Github email"
	email=$ASKUSER

	# Modification git global configuration
	git config --global user.name "$name"
	git config --global user.email "$email"
	git config --global push.default simple
	git config --global credential.helper "cache --timeout=3600"

	/show/listecho "Password is now cached for 15 minutes" $OK
	/show/listecho "http://stackoverflow.com/questions/5343068/is-there-a-way-to-skip-pass" $WARN

fi
