#!/bin/bash

if [ $# -ge 1 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox "$0"
	/show/info '[beta] [interactive] [danger]'
	/show/usageDescription 'Erase last commit on github (use it only on last resort!)'
	/show/usage "$0"
else
	/show/description "Undo last commit ?"
	. /show/continuePrompt
	
	/show/listecho "Are you really sure ?" $ERR
	. /show/continuePrompt

	/show/listecho "git reset --hard HEAD~1"
	git reset --hard HEAD~1
	/do/git/forcesave
fi